include:
  - board: raytac_mdbt50q_rx
    shield: linkup_dongle
  - board: linkup
    shield: linkup_leftcentral
  - board: linkup
    shield: linkup_leftsingle
  - board: linkup
    shield: linkup_rightsingle
  - board: linkup
    shield: linkup_xsingle
