include:
  - board: raytac_mdbt50q_rx
    shield: linkup_dongle
  - board: raytac_mdbt50q_rx
    shield: settings_reset
  - board: linkup
    shield: linkup_leftcentral
  - board: linkup
    shield: linkup_left
  - board: linkup
    shield: linkup_right
  - board: linkup
    shield: linkup_xtra
  - board: linkup
    shield: linkup_test
