include:
  - board: nordic_nrf52840_dongle_slicemk
    shield: linkup_dongle
  - board: linkup
    shield: linkup_left
  - board: linkup
    shield: linkup_right
  - board: linkup
    shield: linkup_x
