include:
  - board: nordic_nrf52840_dongle_slicemk
    shield: linkup_dongle
  - board: linkup_left
    shield: linkup_leftsingle
  - board: linkup_right
    shield: linkup_right
  - board: linkup_x
    shield: linkup_x
