include:
  - board: nordic_nrf52840_dongle_slicemk
    shield: linkup_dongle
  - board: linkup
    shield: linkup_leftcentral
  - board: linkup
    shield: linkup_leftsingle
  - board: linkup
    shield: linkup_rightsingle
  - board: linkup
    shield: linkup_xsingle
